stripeSecretKey = "your_stripe_secret_key"
successRedirectUrl="http://localhost:5173/payment-success"
cancelRedirectUrl="http://localhost:5173/payment-failed"

host = "payment_service_mongodb"
port = 27017
username = "payment-service-db-user"
password = "dbinitPASSWORD001axi00"
database = "payment-service-db"
collection = "payments"

kafkaBootstrapServers = "kafka:9092"