[ride_service]
PORT = 8082
WEBSOCKET_PORT = 27770
pub_key = "./public.crt"

[ride_service.repository]
host = "ride_service_db"
port = 5432
user = "ride_user"
password = "ride_pass"
database = "ride_service_db"

[ride_service.user_service_client.userServiceClient]
url = "http://user_service:5000/user-service"
timeout = 90.0

[ride_service.bike_service_client.bikeServiceClient]
url = "http://bike_service:8090/bike-service"
timeout = 90.0

[ride_service.reward_service_client.rewardServiceClient]
url = "http://reward-service:9092/"
timeout = 90.0

[ride_service.user_service_client.userCapabilityCacheConfig]
capacity = 1000
evictionFactor = 0.25
defaultMaxAge = 300.0
cleanupInterval = 600.0

[ride_service.event_handler]
SERVER_URL = "kafka:9092" 
RIDE_NOTIF_EVENTS_TOPIC = "ride-events"
PAYMENT_EVENTS_TOPIC = "payment-events"	

[ride_service.event_handler.producerConfiguration]
clientId = "event-producer"
acks = "all"
retryCount = 3