[ride_service]
PORT = 8081

[ride_service.repository]
# host = "localhost"
host = "ride_service_db"
port = 5432
user = "ride_user"
password = "ride_pass"
database = "ride_service_db"

[ride_service.user_service_client.userServiceClient]
url = "hh"
timeout = 2.0

[ride_service.bike_service_client.bikeServiceClient]
url = "http://bike_service:8090/bike-service"
timeout = 2.0

[ride_service.reward_service_client.rewardServiceClient]
url = "http://reward_service:8091/"
timeout = 2.0

[ride_service.user_service_client.userCapabilityCacheConfig]
capacity = 1000
evictionFactor = 0.25
defaultMaxAge = 300.0
cleanupInterval = 600.0

[ride_service.event_handler]
SERVER_URL = "kafka:9094"
RIDE_RESERVE_TOPIC = "ride-reserve-topic"	
RIDE_START_TOPIC = "ride-start-topic"
RIDE_END_TOPIC = "ride-end-topic"
RIDE_CANCEL_TOPIC = "ride-cancel-topic"

[ride_service.event_handler.producerConfiguration]
clientId = "event-producer"
acks = "all"
retryCount = 3