pub_key = "./public.crt"

[ride_service]
PORT = 8081

[ride_service.repository]
host = "ride_service_db"
port = 5432
user = "ride_user"
password = "ride_pass"
database = "ride_service_db"

[ride_service.bike_service_client.bikeServiceClient]
url = "http://bike_service:8090/bike-service"
timeout = 2.0

[ride_service.reward_service_client.rewardServiceClient]
url = "http://reward_service:8091/"
timeout = 2.0
